name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # e2e tests
  e2e:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' # secrets not available
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test
        with:
          api-key: ${{ secrets.RAPID_API_KEY }}
          name: opt
      - run: |
          echo "Expired: ${{ steps.test.outputs.expired }}" 
          echo "Expiration date: ${{ steps.test.outputs.expirationDate }}" 
          echo "Day(s) before expiration: ${{ steps.test.outputs.daysBeforeExpiration }}"
